"""empty message

Revision ID: f4df7a4ffafe
Revises: 
Create Date: 2021-02-20 19:53:23.520682

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f4df7a4ffafe'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('room',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('club_id', sa.Integer(), nullable=True),
    sa.Column('user_looked', sa.Boolean(), nullable=True),
    sa.Column('club_looked', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['club_id'], ['club.club_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=True),
    sa.Column('msg', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('user_type', sa.Enum('U', 'C', 'H', name='chatenum'), nullable=True),
    sa.ForeignKeyConstraint(['room_id'], ['room.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint('FK1pcq0qkra6416gd02uo4yl7p2', 'club_head', type_='foreignkey')
    op.create_foreign_key(None, 'club_head', 'club', ['club_id'], ['club_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_constraint(None, 'club_head', type_='foreignkey')
    # op.create_foreign_key('FK1pcq0qkra6416gd02uo4yl7p2', 'club_head', 'club', ['club_id'], ['club_id'])
    # op.create_table('feed_flag',
    # sa.Column('flag_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    # sa.Column('feed_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    # sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    # sa.ForeignKeyConstraint(['feed_id'], ['feed.id'], name='FKmopk9uue6nn0813ur3x5hqu90'),
    # sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], name='FK88a8ii72u22n1jir6go61agec'),
    # sa.PrimaryKeyConstraint('flag_id'),
    # mysql_collate='utf8mb4_0900_ai_ci',
    # mysql_default_charset='utf8mb4',
    # mysql_engine='InnoDB'
    # )
    # op.create_table('feed',
    # sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    # sa.Column('contents', mysql.VARCHAR(length=255), nullable=True),
    # sa.Column('pin', mysql.BIT(length=1), nullable=False),
    # sa.Column('upload_at', mysql.DATETIME(), nullable=True),
    # sa.Column('club_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    # sa.ForeignKeyConstraint(['club_id'], ['club.club_id'], name='FKth0hkc3j007li8ub1sbp1g52o'),
    # sa.PrimaryKeyConstraint('id'),
    # mysql_collate='utf8mb4_0900_ai_ci',
    # mysql_default_charset='utf8mb4',
    # mysql_engine='InnoDB'
    # )
    # op.create_table('club_follow',
    # sa.Column('follow_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    # sa.Column('club_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    # sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    # sa.ForeignKeyConstraint(['club_id'], ['club.club_id'], name='FKlgfg2gyti0e0qplnqqu2lde52'),
    # sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], name='FKq02exjwq52ugc2vp10nf0wqox'),
    # sa.PrimaryKeyConstraint('follow_id'),
    # mysql_collate='utf8mb4_0900_ai_ci',
    # mysql_default_charset='utf8mb4',
    # mysql_engine='InnoDB'
    # )
    # op.create_table('major',
    # sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    # sa.Column('major_name', mysql.VARCHAR(length=45), nullable=True),
    # sa.Column('club_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    # sa.ForeignKeyConstraint(['club_id'], ['club.club_id'], name='FKgwq7aoi3ngn9r0uwhfuf7nls6'),
    # sa.PrimaryKeyConstraint('id'),
    # mysql_collate='utf8mb4_0900_ai_ci',
    # mysql_default_charset='utf8mb4',
    # mysql_engine='InnoDB'
    # )
    # op.create_table('feed_medium',
    # sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    # sa.Column('medium_path', mysql.VARCHAR(length=255), nullable=False),
    # sa.Column('feed_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    # sa.ForeignKeyConstraint(['feed_id'], ['feed.id'], name='FKtjmprshdkigk8369ilwhxg22e'),
    # sa.PrimaryKeyConstraint('id'),
    # mysql_collate='utf8mb4_0900_ai_ci',
    # mysql_default_charset='utf8mb4',
    # mysql_engine='InnoDB'
    # )
    # op.drop_table('chat')
    # op.drop_table('room')
    # ### end Alembic commands ###
