"""empty message

Revision ID: f71d402e05f6
Revises: 
Create Date: 2021-01-29 22:30:32.894783

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f71d402e05f6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('club',
    sa.Column('club_id', sa.Integer(), nullable=False),
    sa.Column('club_name', sa.String(length=45), nullable=True),
    sa.Column('total_budget', sa.Integer(), nullable=True),
    sa.Column('current_budget', sa.Integer(), nullable=True),
    sa.Column('start_at', sa.DateTime(), nullable=True),
    sa.Column('close_at', sa.DateTime(), nullable=True),
    sa.Column('banner_image', sa.String(length=255), nullable=True),
    sa.Column('profile_image', sa.String(length=255), nullable=True),
    sa.Column('hongbo_image', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('club_id')
    )
    op.create_table('user',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=15), nullable=True),
    sa.Column('gcn', sa.String(length=5), nullable=True),
    sa.Column('image_path', sa.String(length=45), nullable=True),
    sa.Column('github_url', sa.String(length=45), nullable=True),
    sa.Column('email', sa.String(length=50), nullable=True),
    sa.Column('device_token', sa.String(length=4096), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('application',
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('club_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('result', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['club_id'], ['club.club_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('application_id')
    )
    op.create_table('club_head',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('club_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['club_id'], ['club.club_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('room',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user', sa.Integer(), nullable=True),
    sa.Column('club_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['club_id'], ['club.club_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=True),
    sa.Column('msg', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('user_type', sa.Enum('U', 'C', 'H', name='chatenum'), nullable=True),
    sa.ForeignKeyConstraint(['room_id'], ['room.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chat')
    op.drop_table('room')
    op.drop_table('club_head')
    op.drop_table('application')
    op.drop_table('user')
    op.drop_table('club')
    # ### end Alembic commands ###
